"
" VIM Conf by Isaac Bythewood
" A hodge-podge of settings I've collected over time, some I might use, some I
" might not anymore.
"


" General Settings
set t_Co=256
colorscheme wombat256mod
set expandtab
set tabstop=4
set shiftwidth=4
set number
syntax on
set nobackup
set nowritebackup
set noswapfile
set autoindent
set cindent
set backspace=indent,eol,start
set ffs=unix,dos
set nocompatible
set laststatus=2
set encoding=utf-8
set nowrap


" Tab Settings
" http://stackoverflow.com/questions/942558/switch-to-specific-tab-in-vim-like-in-firefox
:nnoremap <Esc>1 gt1
:nnoremap <Esc>2 gt2
:nnoremap <Esc>3 gt3
:nnoremap <Esc>4 gt4
:nnoremap <Esc>5 gt5
:nnoremap <Esc>6 gt6
:nnoremap <Esc>7 gt7
:nnoremap <Esc>8 gt8
:nnoremap <Esc>9 gt9
:nnoremap <Esc>0 gt0


" Tab Word Completion
" http://vim.wikia.com/wiki/VimTip566
function! Tab_Or_Complete()
  if col('.')>1 && strpart( getline('.'), col('.')-2, 3 ) =~ '^\w'
    return "\<C-N>"
  else
    return "\<Tab>"
  endif
endfunction
:inoremap <Tab> <C-R>=Tab_Or_Complete()<CR>

