alias ls='LC_COLLATE=C ls --color=auto -h --group-directories-first'

alias v='nvim'
alias vi='nvim'
alias vim='nvim'

alias dps='sudo docker ps -q | xargs sudo docker stats --no-stream'

alias ku='killall -u dev'

alias ri='rm -rf .venv && rm -rf node_modules && mkdir .venv && pipenv install --dev && yarn install'
