# Force tmux into 256 color
alias tmux='TERM=xterm-256color tmux -2'
alias vim='TERM=xterm-256color vim'

# Easy pastebin a file using sprunge
pastebin() {
    cat $1 | curl -F 'sprunge=<-' http://sprunge.us
}

# Shows top 10 most used commands
top10() {
    history | awk 'BEGIN {FS="[ \t]+|\\|"} {print $3}' | sort | uniq -c | sort -nr | head
}

